### ISSUE TITLE
Images relative to footer instead of relative to current page

### ISSUE THREAD

**Issue by applejag** [alertbox/docsify-footer#4] opened 2021-03-03 12:42 UTC
**Is your feature request related to a problem? Please describe.**
If I reference an image then the image link is going to be relative to whichever page I'm viewing.

Example:

```markdown
<!-- same behaviour from all three samples: -->
![company logo](_images/logo.svg)
![company logo](/_images/logo.svg)
![company logo](/_images/logo.svg ':ignore')
```

| On page | it resolves to |
| --- | --- |
| `example.com/#/` | `example.com/_images/logo.svg` ✅ 
| `example.com/#/some-dir/some-other-page` | `example.com/some-dir/_images/logo.svg` :x:

**Describe the solution you'd like**
Don't know if it's possible, but if when resolving the URLs for the images for the footer if those all were based off the location of the `_footer.md` file. So if the footer customly changed to be at `_docsify/footer.md`, then the relative image URL `logo.svg` on `example.com` would look for the image at `example.com/_docsify/logo.svg`, no matter which markdown page is currently being viewed by Docsify.

**Describe alternatives you've considered**
Using absolute link to where we've hosted it. I.e. instead of the above example just using:

```markdown
![company logo](https://example.com/_images/logo.svg)
```

But that makes it more difficult to work with the files locally.

**Comment by kosperera** [comment] 2021-06-05 18:30
@jilleJr The plugin uses docsify underneath to render markdown. You can get a faster response there.
Nevertheless, I think this is a known issue in docsifyjs.

Possible duplicate of:
- https://github.com/docsifyjs/docsify/issues/850
- https://github.com/docsifyjs/docsify/issues/877

**Closed as completed** 2021-09-17 02:42 UTC
Labels: bug, duplicate
